### ISSUE TITLE
you're holding this lock while doing a bunch of I/O, are you sure that's fine?

### ISSUE THREAD

**Issue by ro-tex** [SkynetLabs/pinner#11]
you're holding this lock while doing a bunch of I/O, are you sure that's fine?

_Originally posted by @peterjan in https://github.com/SkynetLabs/pinner/pull/7#discussion_r865697163_

**Comment by ChrisSchinnerl** [comment]
FWIW it's generally discouraged to hold a lock while doing I/O.

I'd recommend using a lock only to create a channel. Then unlocking it immediately and waiting on that channel for the cache update to be done.

**Comment by ro-tex** [comment]
> I'd recommend using a lock only to create a channel. Then unlocking it immediately and waiting on that channel for the cache update to be done.

Sure, this works for me. We're not holding a lock per se but we're not allowing two cache updates to go in parallel.

**Comment by ro-tex** [comment]
From offline:

We discussed the pros and cons and it seems that the simplest solution that gives us practically all we need is to rebuild the cache before each scan and consider it valid throughout the scan.

The only materially different approach would be for `skyd` to keep the cache instead and make sure it stays continually up to date on pin/unpin operations. For the moment this is not going to happen, though, as it has its own implications.
