### ISSUE TITLE
It is still being used as the default sleep time in case we fail to fetch the size of the skyfile from `skyd`.

### ISSUE THREAD

**Issue by ChrisSchinnerl** [SkynetLabs/pinner#13]
It is still being used as the default sleep time in case we fail to fetch the size of the skyfile from `skyd`.

I don't particularly like this approach, so if someone has a suggestion for improving https://github.com/SkynetLabs/pinner/pull/7/files#diff-febdfba77f54946ad0c77a437167750d33fe4aa988fdd0c8935f2fd90cb84442R216, I'd be happy to have it. After we remove it from there, we can remove it completely.

_Originally posted by @ro-tex in https://github.com/SkynetLabs/pinner/pull/7#discussion_r867923261_

**Comment by ro-tex** [comment]
I don't think this issue will gain any attention (in the form of the suggestions I asked for), so having it is only adding noise.

Closing. We can always revisit.
